status = [
  "GitHub CI (Cockroach)"
]
pr_status = [
  "license/cla"
]
block_labels = [
  "do-not-merge"
]
# Set to 4 hours
timeout_sec = 14400

[committer]
name = "craig[bot]"
email = "bors@cockroachlabs.com"
