"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
import version
import platform

osName = "OSX"
version = version.version
cwd = os.getcwd()
APP = ['hmark.py']
APP_NAME = 'hmark_' + version + "_" + osName
DATA_FILES = ['icon.gif', 'ctags']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'icon.gif',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
